spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/notification_db
  
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        auto-startup: true
        acknowledge-mode: auto
    template:
      mandatory: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: mqstream@gmail.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: false #Remove in prod
          ssl:
            trust: "*" #Test purpose, remove in prod
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          debug: true

notification:
  frequency:
    max-daily: 500 # Just to do a small research to know freqency limit of notification, can be ignored
    min-interval-seconds: 2

logging:
  level:
    com.pmtool.notification: DEBUG
    org.springframework.data.mongodb: INFO
    org.springframework.amqp: INFO
    org.springframework.mail: DEBUG
    com.sun.mail: DEBUG

firebase:
  credentials:
    file: classpath:firebase-service-account.json 